#!/usr/bin/env ruby
require 'optparse'
require File.expand_path('bulletin', File.dirname(__FILE__))

ARGV.options do |o|
  Bulletin::App.setup_db
  bulletin = Bulletin::App.new(true)
  bulletin.load_config
  o.set_summary_indent('  ')
  o.banner =    "Usage: #{File.basename($0)} [OPTIONS]"
  o.define_head 'Personalized news client'
  o.on('-o', '--open ID', 'open link') { |id| bulletin.open_item(id); exit }
  o.on('-p', '--page PAGE', 'show page') { |page| bulletin.run(page); exit }
  o.on('-r', '--refresh', 'refresh and ranks stories') { bulletin.refresh; exit }
  o.on('-s', '--save ID', 'save link') { |id| bulletin.save(id); exit }
  o.on('-S', '--saved', 'show all saved') { |id| bulletin.saved; exit }
  o.on('-u', '--unsave ID', 'undo save') { |id| bulletin.unsave(id); exit }
  o.on('-v', '--version', 'show version') do
    puts "bulletin version #{Bulletin::VERSION}"
    exit
  end
  o.on('-h', '--help', 'show this help message') { puts o; exit }
  o.parse!
  ARGV.empty? ? bulletin.run : puts(o)
end
